name 'dhoppe-puppet'
version '0.0.16'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-puppet'
source 'git://github.com/dhoppe/puppet-puppet'
summary 'Puppet Module'
description 'Puppet Module for Debian, Ubuntu'
dependency 'dhoppe/mysql', '>=0.0.1'
dependency 'dhoppe/postgresql', '>=0.0.1'
